import type { MissionDefinition } from "../domain/learning/types";

function s(overrides: Partial<MissionDefinition["initialSettings"]> = {}): MissionDefinition["initialSettings"] {
  return {
    aperture: 4,
    shutterDenominator: 125,
    iso: 400,
    focalLengthMm: 50,
    subjectDistanceM: 2,
    focusMode: "auto-subject",
    focusTargetId: "portrait-subject",
    panningEnabled: false,
    ...overrides,
  };
}

export const MISSIONS: MissionDefinition[] = [
  // Module 1 — Movement
  {
    id: "freeze-runner",
    moduleId: "m1",
    sceneId: "runner",
    titleKey: "mission.freeze-runner.title",
    briefKey: "mission.freeze-runner.brief",
    intentKey: "mission.freeze-runner.intent",
    enabledControls: ["shutter"],
    initialSettings: {
      aperture: 4,
      shutterDenominator: 30,
      iso: 100,
      focalLengthMm: 50,
      subjectDistanceM: 4,
      focusMode: "auto-subject",
      focusTargetId: "runner-subject",
      panningEnabled: false,
    },
    sceneEv100: 11,
    rules: [{ kind: "metric", metric: "motionBlurPx", operator: "<=", value: 4, weight: 1 }],
    hintKeys: ["hint.freeze-runner.1", "hint.freeze-runner.2", "hint.freeze-runner.3"],
    maxVisibleCaptures: 1,
    concepts: ["shutter"],
  },
  {
    id: "motion-and-light",
    moduleId: "m1",
    sceneId: "runner",
    titleKey: "mission.motion-and-light.title",
    briefKey: "mission.motion-and-light.brief",
    intentKey: "mission.motion-and-light.intent",
    enabledControls: ["shutter", "iso"],
    initialSettings: {
      aperture: 4,
      shutterDenominator: 30,
      iso: 100,
      focalLengthMm: 50,
      subjectDistanceM: 4,
      focusMode: "auto-subject",
      focusTargetId: "runner-subject",
      panningEnabled: false,
    },
    sceneEv100: 9,
    rules: [
      { kind: "metric", metric: "motionBlurPx", operator: "<=", value: 6, weight: 0.6 },
      { kind: "metric", metric: "exposureDeltaAbs", operator: "<=", value: 0.75, weight: 0.4 },
    ],
    hintKeys: ["hint.motion-and-light.1", "hint.motion-and-light.2", "hint.motion-and-light.3"],
    maxVisibleCaptures: 2,
    concepts: ["shutter", "iso", "trade-offs"],
  },
  {
    id: "low-light-runner",
    moduleId: "m1",
    sceneId: "runner",
    titleKey: "mission.low-light-runner.title",
    briefKey: "mission.low-light-runner.brief",
    intentKey: "mission.low-light-runner.intent",
    enabledControls: ["shutter", "aperture", "iso"],
    initialSettings: {
      aperture: 4,
      shutterDenominator: 60,
      iso: 400,
      focalLengthMm: 50,
      subjectDistanceM: 4,
      focusMode: "auto-subject",
      focusTargetId: "runner-subject",
      panningEnabled: false,
    },
    sceneEv100: 7,
    rules: [
      { kind: "metric", metric: "motionBlurPx", operator: "<=", value: 7, weight: 0.4 },
      { kind: "metric", metric: "exposureDeltaAbs", operator: "<=", value: 0.75, weight: 0.4 },
      { kind: "metric", metric: "noiseStrength", operator: "<=", value: 0.8, weight: 0.2 },
    ],
    hintKeys: ["hint.low-light-runner.1", "hint.low-light-runner.2", "hint.low-light-runner.3"],
    maxVisibleCaptures: 3,
    concepts: ["shutter", "aperture", "iso", "trade-offs"],
  },

  // Module 2 — Aperture
  {
    id: "separate-subject",
    moduleId: "m2",
    sceneId: "portrait",
    titleKey: "mission.separate-subject.title",
    briefKey: "mission.separate-subject.brief",
    intentKey: "mission.separate-subject.intent",
    enabledControls: ["aperture"],
    initialSettings: s({ aperture: 8, shutterDenominator: 125, iso: 200, focalLengthMm: 50, subjectDistanceM: 2 }),
    sceneEv100: 10,
    rules: [{ kind: "metric", metric: "backgroundBlurPx", operator: ">=", value: 5, weight: 1 }],
    hintKeys: ["hint.separate-subject.1", "hint.separate-subject.2", "hint.separate-subject.3"],
    maxVisibleCaptures: 1,
    concepts: ["aperture"],
  },
  {
    id: "keep-context",
    moduleId: "m2",
    sceneId: "portrait",
    titleKey: "mission.keep-context.title",
    briefKey: "mission.keep-context.brief",
    intentKey: "mission.keep-context.intent",
    enabledControls: ["aperture", "iso"],
    initialSettings: s({ aperture: 2.8, shutterDenominator: 125, iso: 400, focalLengthMm: 50, subjectDistanceM: 2 }),
    sceneEv100: 10,
    rules: [
      { kind: "metric", metric: "backgroundBlurPx", operator: "<=", value: 5, weight: 0.5 },
      { kind: "metric", metric: "exposureDeltaAbs", operator: "<=", value: 0.75, weight: 0.3 },
      { kind: "metric", metric: "noiseStrength", operator: "<=", value: 0.8, weight: 0.2 },
    ],
    hintKeys: ["hint.keep-context.1", "hint.keep-context.2", "hint.keep-context.3"],
    maxVisibleCaptures: 2,
    concepts: ["aperture", "iso"],
  },
  {
    id: "portrait-tradeoff",
    moduleId: "m2",
    sceneId: "portrait",
    titleKey: "mission.portrait-tradeoff.title",
    briefKey: "mission.portrait-tradeoff.brief",
    intentKey: "mission.portrait-tradeoff.intent",
    enabledControls: ["aperture", "shutter", "iso"],
    initialSettings: s({ aperture: 5.6, shutterDenominator: 125, iso: 200, focalLengthMm: 85, subjectDistanceM: 2 }),
    sceneEv100: 10,
    rules: [
      { kind: "metric", metric: "backgroundBlurPx", operator: ">=", value: 4, weight: 0.4 },
      { kind: "metric", metric: "exposureDeltaAbs", operator: "<=", value: 0.75, weight: 0.4 },
      { kind: "metric", metric: "noiseStrength", operator: "<=", value: 0.6, weight: 0.2 },
    ],
    hintKeys: ["hint.portrait-tradeoff.1", "hint.portrait-tradeoff.2", "hint.portrait-tradeoff.3"],
    maxVisibleCaptures: 3,
    concepts: ["aperture", "trade-offs"],
  },

  // Module 3 — ISO and tonal limits
  {
    id: "recover-exposure",
    moduleId: "m3",
    sceneId: "portrait",
    titleKey: "mission.recover-exposure.title",
    briefKey: "mission.recover-exposure.brief",
    intentKey: "mission.recover-exposure.intent",
    enabledControls: ["iso"],
    initialSettings: s({ aperture: 8, shutterDenominator: 500, iso: 100, focalLengthMm: 50, subjectDistanceM: 2 }),
    sceneEv100: 10,
    rules: [{ kind: "metric", metric: "exposureDeltaAbs", operator: "<=", value: 0.75, weight: 1 }],
    hintKeys: ["hint.recover-exposure.1", "hint.recover-exposure.2", "hint.recover-exposure.3"],
    maxVisibleCaptures: 1,
    concepts: ["iso", "stops"],
  },
  {
    id: "avoid-noise",
    moduleId: "m3",
    sceneId: "portrait",
    titleKey: "mission.avoid-noise.title",
    briefKey: "mission.avoid-noise.brief",
    intentKey: "mission.avoid-noise.intent",
    enabledControls: ["aperture", "iso"],
    initialSettings: s({ aperture: 5.6, shutterDenominator: 125, iso: 800, focalLengthMm: 50, subjectDistanceM: 2 }),
    sceneEv100: 10,
    rules: [
      { kind: "metric", metric: "exposureDeltaAbs", operator: "<=", value: 0.75, weight: 0.5 },
      { kind: "metric", metric: "noiseStrength", operator: "<=", value: 0.6, weight: 0.5 },
    ],
    hintKeys: ["hint.avoid-noise.1", "hint.avoid-noise.2", "hint.avoid-noise.3"],
    maxVisibleCaptures: 2,
    concepts: ["iso", "trade-offs"],
  },
  {
    id: "protect-tones",
    moduleId: "m3",
    sceneId: "portrait",
    titleKey: "mission.protect-tones.title",
    briefKey: "mission.protect-tones.brief",
    intentKey: "mission.protect-tones.intent",
    enabledControls: ["shutter", "aperture", "iso"],
    initialSettings: s({ aperture: 4, shutterDenominator: 250, iso: 400, focalLengthMm: 50, subjectDistanceM: 2 }),
    sceneEv100: 11,
    rules: [
      { kind: "metric", metric: "highlightClippingRisk", operator: "<=", value: 0.35, weight: 0.4 },
      { kind: "metric", metric: "shadowLossRisk", operator: "<=", value: 0.35, weight: 0.4 },
      { kind: "metric", metric: "noiseStrength", operator: "<=", value: 0.8, weight: 0.2 },
    ],
    hintKeys: ["hint.protect-tones.1", "hint.protect-tones.2", "hint.protect-tones.3"],
    maxVisibleCaptures: 3,
    concepts: ["iso", "trade-offs"],
  },

  // Module 4 — Exposure as system
  {
    id: "one-stop-exchange",
    moduleId: "m4",
    sceneId: "portrait",
    titleKey: "mission.one-stop-exchange.title",
    briefKey: "mission.one-stop-exchange.brief",
    intentKey: "mission.one-stop-exchange.intent",
    enabledControls: ["aperture", "shutter"],
    initialSettings: s({ aperture: 4, shutterDenominator: 125, iso: 200, focalLengthMm: 50, subjectDistanceM: 2 }),
    sceneEv100: 10,
    rules: [
      { kind: "metric", metric: "exposureDeltaAbs", operator: "<=", value: 0.5, weight: 0.6 },
      { kind: "setting-stop-delta", setting: "aperture", minStops: 2, weight: 0.4 },
    ],
    hintKeys: ["hint.one-stop-exchange.1", "hint.one-stop-exchange.2", "hint.one-stop-exchange.3"],
    maxVisibleCaptures: 2,
    concepts: ["stops", "aperture", "shutter"],
  },
  {
    id: "same-exposure-different-image",
    moduleId: "m4",
    sceneId: "runner",
    titleKey: "mission.same-exposure-different-image.title",
    briefKey: "mission.same-exposure-different-image.brief",
    intentKey: "mission.same-exposure-different-image.intent",
    enabledControls: ["aperture", "shutter", "iso"],
    initialSettings: s({
      aperture: 4,
      shutterDenominator: 125,
      iso: 200,
      focalLengthMm: 50,
      subjectDistanceM: 4,
      focusTargetId: "runner-subject",
    }),
    sceneEv100: 10,
    rules: [
      { kind: "all-retained-captures-metric", metric: "exposureDeltaAbs", operator: "<=", value: 0.5, minCaptures: 2, weight: 0.5 },
      { kind: "pair-metric-delta", metric: "motionBlurPx", operator: ">=", value: 6, weight: 0.5 },
    ],
    hintKeys: [
      "hint.same-exposure-different-image.1",
      "hint.same-exposure-different-image.2",
      "hint.same-exposure-different-image.3",
    ],
    maxVisibleCaptures: 2,
    concepts: ["stops", "shutter", "trade-offs"],
  },
  {
    id: "choose-the-compromise",
    moduleId: "m4",
    sceneId: "runner",
    titleKey: "mission.choose-the-compromise.title",
    briefKey: "mission.choose-the-compromise.brief",
    intentKey: "mission.choose-the-compromise.intent",
    enabledControls: ["aperture", "shutter", "iso"],
    initialSettings: s({
      aperture: 4,
      shutterDenominator: 60,
      iso: 400,
      focalLengthMm: 50,
      subjectDistanceM: 4,
      focusTargetId: "runner-subject",
    }),
    sceneEv100: 7,
    rules: [
      { kind: "metric", metric: "motionBlurPx", operator: "<=", value: 7, weight: 0.4 },
      { kind: "metric", metric: "exposureDeltaAbs", operator: "<=", value: 0.75, weight: 0.4 },
      { kind: "metric", metric: "noiseStrength", operator: "<=", value: 0.7, weight: 0.2 },
    ],
    hintKeys: ["hint.choose-the-compromise.1", "hint.choose-the-compromise.2", "hint.choose-the-compromise.3"],
    maxVisibleCaptures: 3,
    concepts: ["trade-offs"],
  },

  // Module 5 — Optics and spatial
  {
    id: "change-field-of-view",
    moduleId: "m5",
    sceneId: "portrait",
    titleKey: "mission.change-field-of-view.title",
    briefKey: "mission.change-field-of-view.brief",
    intentKey: "mission.change-field-of-view.intent",
    enabledControls: ["focalLength"],
    initialSettings: s({ focalLengthMm: 50, subjectDistanceM: 2, aperture: 5.6, shutterDenominator: 125, iso: 200 }),
    sceneEv100: 10,
    rules: [
      { kind: "pair-metric-delta", metric: "horizontalFovDeg", operator: ">=", value: 20, weight: 0.6 },
      { kind: "distinct-setting-count", setting: "focalLengthMm", minDistinct: 2, weight: 0.4 },
    ],
    hintKeys: ["hint.change-field-of-view.1", "hint.change-field-of-view.2", "hint.change-field-of-view.3"],
    maxVisibleCaptures: 2,
    concepts: ["focal-length"],
  },
  {
    id: "distance-and-background",
    moduleId: "m5",
    sceneId: "portrait",
    titleKey: "mission.distance-and-background.title",
    briefKey: "mission.distance-and-background.brief",
    intentKey: "mission.distance-and-background.intent",
    enabledControls: ["focalLength", "subjectDistance"],
    initialSettings: s({ focalLengthMm: 35, subjectDistanceM: 2, aperture: 2.8, shutterDenominator: 125, iso: 200 }),
    sceneEv100: 10,
    rules: [
      { kind: "framing-similarity", maxRelativeDifference: 0.15, minCaptures: 2, weight: 0.5 },
      { kind: "pair-metric-delta", metric: "backgroundBlurPx", operator: ">=", value: 3, weight: 0.5 },
    ],
    hintKeys: ["hint.distance-and-background.1", "hint.distance-and-background.2", "hint.distance-and-background.3"],
    maxVisibleCaptures: 3,
    concepts: ["focal-length", "distance", "focus"],
  },
  {
    id: "choose-focus",
    moduleId: "m5",
    sceneId: "depth",
    titleKey: "mission.choose-focus.title",
    briefKey: "mission.choose-focus.brief",
    intentKey: "mission.choose-focus.intent",
    enabledControls: ["aperture", "focalLength", "focusTarget"],
    initialSettings: s({
      aperture: 4,
      focalLengthMm: 50,
      subjectDistanceM: 2,
      focusTargetId: "depth-foreground",
      focusMode: "target",
      shutterDenominator: 125,
      iso: 200,
    }),
    sceneEv100: 10,
    rules: [
      { kind: "metric", metric: "foregroundBlurPx", operator: "<=", value: 5, weight: 0.5 },
      { kind: "metric", metric: "backgroundBlurPx", operator: ">=", value: 4, weight: 0.5 },
    ],
    hintKeys: ["hint.choose-focus.1", "hint.choose-focus.2", "hint.choose-focus.3"],
    maxVisibleCaptures: 3,
    concepts: ["focus", "aperture"],
  },
];

export const TRANSFER_MISSIONS: MissionDefinition[] = [
  {
    id: "editorial-portrait",
    moduleId: "transfer",
    sceneId: "portrait",
    titleKey: "mission.editorial-portrait.title",
    briefKey: "mission.editorial-portrait.brief",
    intentKey: "mission.editorial-portrait.intent",
    enabledControls: ["aperture", "shutter", "iso", "focalLength"],
    initialSettings: s({ aperture: 4, shutterDenominator: 125, iso: 200, focalLengthMm: 85, subjectDistanceM: 2 }),
    sceneEv100: 10,
    rules: [
      { kind: "metric", metric: "backgroundBlurPx", operator: ">=", value: 5, weight: 0.4 },
      { kind: "metric", metric: "backgroundBlurPx", operator: "<=", value: 10, weight: 0.2 },
      { kind: "metric", metric: "noiseStrength", operator: "<=", value: 0.6, weight: 0.4 },
    ],
    hintKeys: ["hint.editorial-portrait.1", "hint.editorial-portrait.2", "hint.editorial-portrait.3"],
    maxVisibleCaptures: 5,
    concepts: ["trade-offs"],
  },
  {
    id: "runner-at-dusk",
    moduleId: "transfer",
    sceneId: "runner",
    titleKey: "mission.runner-at-dusk.title",
    briefKey: "mission.runner-at-dusk.brief",
    intentKey: "mission.runner-at-dusk.intent",
    enabledControls: ["aperture", "shutter", "iso"],
    initialSettings: s({
      aperture: 2.8,
      shutterDenominator: 60,
      iso: 800,
      focalLengthMm: 50,
      subjectDistanceM: 4,
      focusTargetId: "runner-subject",
    }),
    sceneEv100: 7,
    rules: [
      { kind: "metric", metric: "motionBlurPx", operator: "<=", value: 7, weight: 0.4 },
      { kind: "metric", metric: "exposureDeltaAbs", operator: "<=", value: 0.75, weight: 0.4 },
      { kind: "metric", metric: "noiseStrength", operator: "<=", value: 0.7, weight: 0.2 },
    ],
    hintKeys: ["hint.runner-at-dusk.1", "hint.runner-at-dusk.2", "hint.runner-at-dusk.3"],
    maxVisibleCaptures: 5,
    concepts: ["trade-offs"],
  },
  {
    id: "intentional-panning",
    moduleId: "transfer",
    sceneId: "runner",
    titleKey: "mission.intentional-panning.title",
    briefKey: "mission.intentional-panning.brief",
    intentKey: "mission.intentional-panning.intent",
    enabledControls: ["shutter", "panning"],
    initialSettings: {
      aperture: 8,
      shutterDenominator: 30,
      iso: 100,
      focalLengthMm: 50,
      subjectDistanceM: 4,
      focusMode: "auto-subject",
      focusTargetId: "runner-subject",
      panningEnabled: false,
    },
    sceneEv100: 11,
    rules: [
      { kind: "metric", metric: "motionBlurPx", operator: "<=", value: 8, weight: 0.4 },
      { kind: "metric", metric: "backgroundMotionBlurPx", operator: ">=", value: 10, weight: 0.6 },
    ],
    hintKeys: ["hint.intentional-panning.1", "hint.intentional-panning.2", "hint.intentional-panning.3"],
    maxVisibleCaptures: 5,
    concepts: ["shutter", "trade-offs"],
  },
];
